# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='bt.proto',
  package='rtkaczyk.eris.bluetooth',
  serialized_pb='\n\x08\x62t.proto\x12\x17rtkaczyk.eris.bluetooth\"U\n\x07Request\x12\x0c\n\x04\x66r0m\x18\x01 \x01(\x06\x12\n\n\x02to\x18\x02 \x01(\x06\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\r\n\x05\x62\x61tch\x18\x04 \x01(\x05\x12\x12\n\x04\x66ull\x18\x05 \x01(\x08:\x04true\"\x98\x01\n\x08Response\x12\x0c\n\x04\x66r0m\x18\x01 \x01(\x06\x12\n\n\x02to\x18\x02 \x01(\x06\x12\x30\n\x07packets\x18\x03 \x03(\x0b\x32\x1f.rtkaczyk.eris.bluetooth.Packet\x12\x11\n\tnoPackets\x18\x04 \x01(\x05\x12-\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x1e.rtkaczyk.eris.bluetooth.Error\")\n\x06Packet\x12\x11\n\ttimestamp\x18\x01 \x01(\x06\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"\x96\x01\n\x05\x45rror\x12\x31\n\x04\x63ode\x18\x01 \x02(\x0e\x32#.rtkaczyk.eris.bluetooth.Error.Code\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"E\n\x04\x43ode\x12\x14\n\x10\x43ONNECTION_ERROR\x10\x00\x12\x13\n\x0fINVALID_REQUEST\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x42\x0c\x42\nBtMessages')



_ERROR_CODE = descriptor.EnumDescriptor(
  name='Code',
  full_name='rtkaczyk.eris.bluetooth.Error.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=404,
  serialized_end=473,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='rtkaczyk.eris.bluetooth.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fr0m', full_name='rtkaczyk.eris.bluetooth.Request.fr0m', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='rtkaczyk.eris.bluetooth.Request.to', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit', full_name='rtkaczyk.eris.bluetooth.Request.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='batch', full_name='rtkaczyk.eris.bluetooth.Request.batch', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='full', full_name='rtkaczyk.eris.bluetooth.Request.full', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=122,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='rtkaczyk.eris.bluetooth.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fr0m', full_name='rtkaczyk.eris.bluetooth.Response.fr0m', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='rtkaczyk.eris.bluetooth.Response.to', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packets', full_name='rtkaczyk.eris.bluetooth.Response.packets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='noPackets', full_name='rtkaczyk.eris.bluetooth.Response.noPackets', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='rtkaczyk.eris.bluetooth.Response.error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=277,
)


_PACKET = descriptor.Descriptor(
  name='Packet',
  full_name='rtkaczyk.eris.bluetooth.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='rtkaczyk.eris.bluetooth.Packet.timestamp', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='rtkaczyk.eris.bluetooth.Packet.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=279,
  serialized_end=320,
)


_ERROR = descriptor.Descriptor(
  name='Error',
  full_name='rtkaczyk.eris.bluetooth.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='rtkaczyk.eris.bluetooth.Error.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='rtkaczyk.eris.bluetooth.Error.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERROR_CODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=323,
  serialized_end=473,
)

_RESPONSE.fields_by_name['packets'].message_type = _PACKET
_RESPONSE.fields_by_name['error'].message_type = _ERROR
_ERROR.fields_by_name['code'].enum_type = _ERROR_CODE
_ERROR_CODE.containing_type = _ERROR;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['Error'] = _ERROR

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:rtkaczyk.eris.bluetooth.Request)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:rtkaczyk.eris.bluetooth.Response)

class Packet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKET
  
  # @@protoc_insertion_point(class_scope:rtkaczyk.eris.bluetooth.Packet)

class Error(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERROR
  
  # @@protoc_insertion_point(class_scope:rtkaczyk.eris.bluetooth.Error)

# @@protoc_insertion_point(module_scope)
